### ISSUE TITLE
Use libbpf to create & attach eBPF programs to TC hook

### ISSUE THREAD

**Issue by osinstom** [P4-Research/psabpf#1]
So far, we have been invoking system command (tc ...) to inject TC programs. However, the newest version of libbpf comes with new functions allowing to create and attach eBPF programs to TC hook:

https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L686

We should use them in `psabpf` library.

**Comment by tatry** [comment]
See also [this commit](https://github.com/libbpf/libbpf/commit/d71ff87a2dd7b92787719aab233767e9c74fbd48) in `libbpf`.
